apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: andresvidal/rpi3-mongodb3
          ports:
            - containerPort: 27017
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10	
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-service
  labels:
    app: mongo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-service
  template:
    metadata:
      labels:
        app: mongo-service
    spec:
      containers:
        - name: mongo-service
          image: puunsn/mongo-service
          ports:
            - containerPort: 3001
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-service
  labels:
    app: todolist-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-service
  template:
    metadata:
      labels:
        app: todolist-service
    spec:
      containers:
        - name: todolist-service
          image: puunsn/todolist:latest
          ports:
            - containerPort: 80
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: puunsn/user-service:latest
          ports:
            - containerPort: 3002
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
  labels:
    app: management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
        - name: management-service
          image: puunsn/todo_management-service:latest
          ports:
            - containerPort: 3003
      tolerations:
        - key: 'node.kubernetes.io/unreachable'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
        - key: 'node.kubernetes.io/not-ready'
          operator: 'Exists'
          effect: 'NoExecute'
          tolerationSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
spec:
  type: NodePort
  selector:
    app: todolist-service
  ports:
  - name: http
    port: 80
    nodePort: 30001
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
  - name: http
    port: 3002
    nodePort: 30002
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  type: NodePort
  selector:
    app: mongo-service
  ports:
  - name: http
    port: 3001
    nodePort: 30003
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: management-service
spec:
  type: NodePort
  selector:
    app: management-service
  ports:
  - name: http
    port: 3003
    nodePort: 30004
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: NodePort
  selector:
    app: mongo
  ports:
  - name: http
    port: 27017
    nodePort: 30005
